import { useState, useRef, useEffect } from 'react';
import gsap from 'gsap';

function FooterModal({ icon, title, children, onClose }) {
  const overlayRef = useRef(null);
  const cardRef    = useRef(null);

  useEffect(() => {
    gsap.fromTo(overlayRef.current, { opacity: 0 }, { opacity: 1, duration: 0.22 });
    gsap.fromTo(cardRef.current,
      { opacity: 0, scale: 0.86, y: 20 },
      { opacity: 1, scale: 1, y: 0, duration: 0.35, ease: 'back.out(1.5)' }
    );
  }, []);

  const handleClose = () => {
    gsap.to(cardRef.current, { opacity: 0, scale: 0.88, y: 12, duration: 0.18, ease: 'power2.in' });
    gsap.to(overlayRef.current, { opacity: 0, duration: 0.2, onComplete: onClose });
  };

  return (
    <div ref={overlayRef} className="modal-overlay" onClick={e => e.target === overlayRef.current && handleClose()}>
      <div ref={cardRef} className="footer-modal sketch-card">
        <button className="footer-modal-close" onClick={handleClose}>
          <i className="bx bx-x" />
        </button>
        <div className="footer-modal-pin">
          <i className={`bx ${icon}`} />
        </div>
        <h2>{title}</h2>
        {children}
      </div>
    </div>
  );
}

export default function Footer({ onSuggest }) {
  const [showTerms, setShowTerms] = useState(false);
  const [showAbout, setShowAbout] = useState(false);

  return (
    <footer className="app-footer">
      <div className="footer-inner">
        <div className="footer-brand">
          <div className="footer-logo-row">
            <img src="/logo.png" alt="Recallify" className="footer-logo-img" />
            <span className="footer-logo">Recallify</span>
          </div>
          <p className="footer-tagline">
            <i className="bx bx-pencil" /> Study smarter, not harder
          </p>
        </div>

        <nav className="footer-links">
          <button id="footer-btn-suggest" className="footer-link" onClick={onSuggest}>
            <i className="bx bx-message-detail" /> Suggestions
          </button>
          <button id="footer-btn-about" className="footer-link" onClick={() => setShowAbout(true)}>
            <i className="bx bx-info-circle" /> About
          </button>
          <button id="footer-btn-terms" className="footer-link" onClick={() => setShowTerms(true)}>
            <i className="bx bx-file" /> Terms
          </button>
          <a
            href="https://github.com/Tsarles"
            target="_blank"
            rel="noopener noreferrer"
            className="footer-link footer-github"
            id="footer-github-link"
          >
            <i className="bx bxl-github" /> @Tsarles2026
          </a>
        </nav>
      </div>

      <div className="footer-bottom">
        <p>
          <i className="bx bx-copyright" /> 2026 Recallify
          &nbsp;·&nbsp; Built by <strong>@Tsarles2026</strong>
          &nbsp;·&nbsp; <i className="bx bx-lock" /> All data stays in your browser
        </p>
      </div>

      {/* About modal */}
      {showAbout && (
        <FooterModal icon="bx-info-circle" title="About Recallify" onClose={() => setShowAbout(false)}>
          <p>
            Recallify is a free, no-sign-up flashcard and quiz tool built for students and self-learners.
            Simply paste quiz questions generated by any AI (ChatGPT, Gemini, etc.) and Recallify
            instantly converts them into interactive study decks.
          </p>
          <ul>
            <li><i className="bx bx-check" /> Up to <strong>5 active decks</strong> stored in your browser</li>
            <li><i className="bx bx-time" /> Per-card timer — adjustable from 10s to 5 minutes</li>
            <li><i className="bx bx-shuffle" /> Questions shuffled randomly every round</li>
            <li><i className="bx bx-hide" /> Reveal answer up to 3 times per quiz</li>
            <li><i className="bx bx-bar-chart-alt-2" /> Score tracking + wrong answer review</li>
            <li><i className="bx bx-archive" /> Archive decks (auto-deleted after 30 days)</li>
            <li><i className="bx bx-pencil" /> Edit decks anytime after creation</li>
            <li><i className="bx bx-user-x" /> Zero sign-up, zero data leaves your device</li>
          </ul>
          <p className="footer-modal-credit">
            Made with <i className="bx bxs-heart" style={{ color: 'var(--wrong)' }} /> by{' '}
            <a href="https://github.com/Tsarles" target="_blank" rel="noopener noreferrer">@Tsarles2026</a>
          </p>
        </FooterModal>
      )}

      {/* Terms modal */}
      {showTerms && (
        <FooterModal icon="bx-file" title="Terms of Use" onClose={() => setShowTerms(false)}>
          <p><strong>Last updated:</strong> March 2026</p>
          <ul>
            <li>Recallify is provided as-is, free of charge.</li>
            <li>All data (decks, scores) is stored locally in your browser via localStorage. We do not collect, transmit, or store your personal data on any server — except for suggestions you choose to submit via the form.</li>
            <li>Suggestions submitted through the form are sent to the developer for product improvement only.</li>
            <li>You are responsible for the content of the quiz questions you paste into the app.</li>
            <li>We reserve the right to update these terms at any time. Continued use constitutes acceptance.</li>
          </ul>
          <p style={{ marginTop: 14, fontSize: '0.88rem', color: 'var(--ink-faded)' }}>
            Questions? Reach out on GitHub:{' '}
            <a href="https://github.com/Tsarles" target="_blank" rel="noopener noreferrer">@Tsarles2026</a>
          </p>
        </FooterModal>
      )}

      <style>{`
        .app-footer {
          background: #fff;
          border-top: 2.5px solid var(--ink);
          margin-top: auto;
        }
        .footer-inner {
          max-width: 900px;
          margin: 0 auto;
          padding: 28px 24px 20px;
          display: flex;
          align-items: flex-start;
          justify-content: space-between;
          gap: 20px;
          flex-wrap: wrap;
        }
        .footer-logo-row {
          display: flex;
          align-items: center;
          gap: 8px;
          margin-bottom: 4px;
        }
        .footer-logo-img {
          width: 28px;
          height: 28px;
          object-fit: contain;
        }
        .footer-logo {
          font-family: var(--font-display);
          font-size: 1.4rem;
          font-weight: 700;
          color: var(--ink);
        }
        .footer-tagline {
          font-size: 0.88rem;
          color: var(--ink-faded);
          display: flex;
          align-items: center;
          gap: 5px;
        }
        .footer-links {
          display: flex;
          gap: 6px;
          flex-wrap: wrap;
          align-items: center;
        }
        .footer-link {
          display: inline-flex;
          align-items: center;
          gap: 6px;
          font-family: var(--font-body);
          font-size: 0.9rem;
          padding: 6px 14px;
          border-radius: 99px;
          border: 1.5px solid var(--border);
          background: transparent;
          color: var(--ink-light);
          cursor: pointer;
          transition: border-color 0.15s, color 0.15s, background 0.15s;
          text-decoration: none;
        }
        .footer-link:hover {
          border-color: var(--ink);
          color: var(--ink);
          background: var(--paper-dark);
        }
        .footer-github {
          border-color: var(--ink);
          font-weight: 600;
          background: var(--paper-dark);
        }
        .footer-github:hover {
          background: var(--ink);
          color: var(--paper) !important;
        }
        .footer-bottom {
          border-top: 1.5px dashed var(--border);
          text-align: center;
          padding: 12px 24px;
          font-size: 0.82rem;
          color: var(--ink-faded);
          display: flex;
          justify-content: center;
          align-items: center;
        }
        .footer-bottom p {
          display: flex;
          align-items: center;
          gap: 4px;
          flex-wrap: wrap;
          justify-content: center;
        }

        /* Modal */
        .footer-modal {
          width: min(560px, 92vw);
          padding: 44px 32px 28px;
          position: relative;
          max-height: 82vh;
          overflow-y: auto;
        }
        .footer-modal-pin {
          position: absolute;
          top: -14px; left: 50%;
          transform: translateX(-50%);
          font-size: 1.5rem;
          background: var(--yellow-bg);
          border: 2px solid var(--ink);
          border-radius: 50%;
          width: 36px; height: 36px;
          display: flex; align-items: center; justify-content: center;
          box-shadow: 2px 2px 0 var(--ink);
        }
        .footer-modal-pin i { font-size: 1.1rem; color: var(--ink); }
        .footer-modal-close {
          position: absolute;
          top: 10px; right: 10px;
          background: var(--paper-dark);
          border: 1.5px solid var(--border);
          border-radius: 50%;
          width: 30px; height: 30px;
          display: flex; align-items: center; justify-content: center;
          cursor: pointer;
          font-size: 1.15rem;
          color: var(--ink-light);
          transition: background 0.15s;
        }
        .footer-modal-close:hover { background: var(--paper-cream); }
        .footer-modal h2 {
          font-size: 1.5rem;
          margin-bottom: 14px;
        }
        .footer-modal p {
          font-size: 0.95rem;
          color: var(--ink-light);
          line-height: 1.65;
          margin-bottom: 10px;
        }
        .footer-modal ul {
          padding-left: 4px;
          color: var(--ink-light);
          font-size: 0.93rem;
          line-height: 1.7;
          margin-bottom: 10px;
          list-style: none;
        }
        .footer-modal ul li {
          display: flex;
          align-items: baseline;
          gap: 7px;
          margin-bottom: 5px;
        }
        .footer-modal ul li i { color: var(--purple); flex-shrink: 0; font-size: 0.9rem; }
        .footer-modal a {
          color: var(--purple);
          text-decoration: underline;
        }
        .footer-modal-credit {
          font-size: 0.88rem !important;
          color: var(--ink-faded) !important;
          margin-top: 16px !important;
          display: flex !important;
          align-items: center;
          gap: 4px;
          flex-wrap: wrap;
        }

        @media (max-width: 480px) {
          .footer-inner { padding: 20px 16px; }
          .footer-links { gap: 4px; }
          .footer-link  { font-size: 0.82rem; padding: 5px 10px; }
        }
      `}</style>
    </footer>
  );
}
